name: Пример рабочего процесса

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Проверка кода
        uses: actions/checkout@v2
      - name: Запуск скрипта
        run: echo "ccc"
